config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'static_pages#home'
  get '/about_us', to: 'static_pages#about_us'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/catalog', to: 'static_pages#catalog'
  get '/pricing', to: 'static_pages#pricing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :referred_by_who
  before_action :home?
  before_action :navigation_type
  after_action :save_prev_route


  def home
    @referred_by = request.referrer
  end

  def about_us
  end

  def contact_us
  end

  def catalog
  end

  def pricing
  end

  def referred_by_who
    @referred_by = request.referrer
  end

  def home?
    @on_home = params[:controller] == 'static_pages' && params[:action] == 'home'
  end

  def save_prev_route
    session[:prev_controller] = params[:controller]
    session[:prev_action] = params[:action]
  end

  def navigation_type
    p '@referred_by.present? => ' + @referred_by.present?.to_s
    p 'session[:prev_action] => ' + session[:prev_action].to_s 
    if !@referred_by.present? && params[:action] == 'home'
      p 'navigation-enter-animate'
      @navigation_type = 'enter-animate'
    elsif !@referred_by.present? && params[:action] != 'home'
      p 'navigation-tab'
      @navigation_type = 'tab'
    elsif @referred_by.present? && session[:prev_action] == 'home' && params[:action] != 'home'
      p 'navigation-tab-animate'
      @navigation_type = 'tab-animate'
    elsif @referred_by.present? && session[:prev_action] == 'home' && params[:action] == 'home'
      p 'navigation-home'
      @navigation_type = 'home'
    elsif @referred_by.present? && session[:prev_action] != 'home' && params[:action] == 'home'
      p 'navigation-home-animate'
      @navigation_type = 'home-animate'
    elsif @referred_by.present? && session[:prev_action] != 'home' && params[:action] != 'home'
      p 'navigation-tab'
      @navigation_type = 'tab'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_bergen_bread_banner.html.erb
<div class="<%= request.referrer.present? ? 'bergen-bread-banner' : 'bergen-bread-banner-animate' %>">
	BERGEN BREAD DIST.
</div>

app/views/layouts/_copyright.html.erb
<div class="copyright">
	Bergen Bread Distribution © 2019
</div>

app/views/layouts/_navigation.html.erb
<div class='navigation'>
	<div class=<%= @navigation_type %>>
		<%= link_to "home", home_path, :class => params[:action] == 'home' ? 'active' : '' %>
		<%= link_to "about us", about_us_path, :class => params[:action] == 'about_us' ? 'active' : ''   %>
		<%= link_to "contact us", contact_us_path, :class => params[:action] == 'contact_us' ? 'active' : '' %>
		<%= link_to "catalog", catalog_path, :class => params[:action] == 'catalog' ? 'active' : '' %>
		<%= link_to "pricing", pricing_path, :class => params[:action] == 'pricing' ? 'active' : '' %>
	</div>
</div>

app/views/layouts/_quick_contact.html.erb
<div class="<%= @referred_by.nil? ? 'quick-contact-animate' : 'quick-contact' %>">
<p>
	<span>phone: 555-555-5555</span>
	<span>email: bergenbread@bergenbread.com</span>
</p>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bergen Bread Distribution</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <div class="container visiblity:hidden">
      <%= render 'layouts/quick_contact' %>
      <%= render 'layouts/bergen_bread_banner' %>
      <%= render 'layouts/navigation' %>
      <%= yield %>
      <%= render 'layouts/copyright' %>
    </div>
  </body>
</html>

app/views/static_pages/about_us.html.erb
<div class="content">
	About us
</div>

app/views/static_pages/catalog.html.erb
<div class="content">
	Catalog
</div>

app/views/static_pages/contact_us.html.erb
<div class="content">
	Contact us
</div>

app/views/static_pages/home.html.erb
<div class="content" style="visibility:hidden">
	Content
</div>

app/views/static_pages/pricing.html.erb
<div class="content">
	Pricing
</div>